package carriers

const (
	NZCourierPostPackageA4BUBBLETRACKPAK    = "A4BUBBLETRACKPAK"
	NZCourierPostPackageA4TRACKPAK          = "A4TRACKPAK"
	NZCourierPostPackageA5BUBBLETRACKPAK    = "A5BUBBLETRACKPAK"
	NZCourierPostPackageA5TRACKPAK          = "A5TRACKPAK"
	NZCourierPostPackageDLETRACKPAK         = "DLETRACKPAK"
	NZCourierPostPackageECOA5TRACKPAK       = "ECOA5TRACKPAK"
	NZCourierPostPackageECODLETRACKPAK      = "ECODLETRACKPAK"
	NZCourierPostPackageECOFOOLSCAPTRACKPAK = "ECOFOOLSCAPTRACKPAK"
	NZCourierPostPackageFOOLSCAPTRACKPAK    = "FOOLSCAPTRACKPAK"
	NZCourierPostPackageLINEFLOWTRACKPAK    = "LINEFLOWTRACKPAK"
	NZCourierPostPackageXTRALARGETRACKPAK   = "XTRALARGETRACKPAK"
)
